[toolchain]
channel = "nightly"
components = ["rustfmt", "rustc-dev"]
# targets = ["xtensa-esp32s3-none-elf"]
# targets = ["xtensa-esp32-none-elf", "xtensa-esp32s2-none-elf","xtensa-esp32s3-none-elf"]
