[build]
# Uncomment the relevant target for your chip here (ESP32, ESP32-S2, ESP32-S3 or ESP32-C3)
target = "xtensa-esp32-espidf"
#target = "xtensa-esp32s2-espidf"
#target = "xtensa-esp32s3-espidf"
#target = "riscv32imc-esp-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# runner = "wokwi-server --chip esp32 --id 331440829570744915"
runner = "web-flash --chip esp32"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
# runner = "wokwi-server --chip esp32s2 --id 330831847505265234"
runner = "web-flash --chip esp32s2"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
runner = "web-flash --chip esp32s3"

[target.riscv32imc-esp-espidf]
linker = "ldproxy"
# runner = "wokwi-server --chip esp32c3 --id 330910629554553426"
runner = "web-flash --chip esp32c3"



# Future - necessary for the experimental "native build" of esp-idf-sys with ESP32C3
# See also https://github.com/ivmarkov/embuild/issues/16
rustflags = ["-C", "default-linker-libraries"]


[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"] # Temporarily comment this out, because of https://github.com/rust-lang/cargo/issues/10019
